import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://nwc-portal-dev.united-builders.net/en');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.getByLabel('Email or username').click();
  await page.getByLabel('Email or username').fill('mona');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('monaqc123*_A12');
  await page.waitForTimeout(5000)
  await page.getByRole('button', { name: 'Submit' }).click();
  //await page.getByText('Mona Mohamed').first().click();
  //await page.getByText('Personal profile Breadcrumb Home mona Primary tabs Profile home(active tab)').click();
  await page.getByRole('link', { name: 'Services' }).click();
  await expect(page.getByLabel('Categories')).toBeVisible();
  await expect(page.getByLabel('Service name')).toBeVisible();
  await page.locator('.order-1 > .region').click();
  await page.getByLabel('Categories').selectOption('7');
  await expect(page.locator('div:nth-child(7)')).toBeVisible();
  await expect(page.locator('div:nth-child(5)').first()).toBeVisible();
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('pro');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('prod');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('prod');
  //await page.getByText('No Services are currently').click();
  await expect(page.getByText('No Services are currently')).toBeVisible();
  await expect(page.locator('#block-nwc-theme-content')).toContainText('No Services are currently available.');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('pro');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('prod');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('product');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('product');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('product ');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('product th');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('product three');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').press('Enter');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').fill('product Three');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').press('Enter');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').press('ArrowLeft');
  await page.getByLabel('Service name').fill('Product Three');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').press('Enter');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('Product ');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('Product ');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('Product_');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('Product_4');
  await page.getByLabel('Service name').click();
  await page.getByText('No Services are currently').click();
  await expect(page.getByText('No Services are currently')).toBeVisible();
  await page.getByText('No Services are currently').click();
  await page.getByText('No Services are currently').click();
  await page.getByLabel('Categories').selectOption('All');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').press('Enter');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('');
  await page.getByLabel('Service name').click();
  await page.getByLabel('Service name').fill('One');
  await expect(page.getByLabel('Service name')).toBeVisible();
  await expect(page.locator('.card-link')).toBeVisible();
  await page.locator('.card-link').click();
  await expect(page.locator('#block-nwc-theme-content')).toContainText('Product One Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy… Details');
  await page.getByRole('button', { name: 'user profile Welcome Mona' }).click();
  await page.getByRole('link', { name: 'My account' }).click();
  await page.getByRole('button', { name: 'user profile Welcome Mona' }).click();
  await page.getByRole('link', { name: 'Log out' }).click();
});